---
# tasks file for roles/python3

- name: Install packages from apt
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python3-pip
    - python3-venv
    - python3-dev
    - python3-mysqldb
